#!/bin/bash

echo "Arcticcoin Logwatch Robot started..."
echo "Donations are welcome:"
echo "Arcticcoin: AHzbs6oFvWmpbHCwRhEHK7WkrXBNt5wp2r "
echo "Bitcoin: 18EmbsmuZPfur8uS2hNirx47gWc26yAQS2 "
echo "Eth: 0x9f322ea2f4dd8bbc1e02a7879e74fb01914192c6 "

tail -fn100 /root/.arcticcore/debug.log | \
while read line ; do
        blok=$( echo "$line" | grep "InvalidChainFound: invalid block=" | grep -Po '[A-Za-z\d]{64}' )
	if [ $? = 0 ]
	 then
	/usr/local/bin/arcticcoin-cli mnsync reset
        /usr/local/bin/arcticcoin-cli reconsiderblock $blok
	/usr/local/bin/arcticcoin-cli clearbanned
	dt=$(date '+%d/%m/%Y %H:%M:%S');
	echo "$dt"
	echo "Masternode reset occured"
	echo "Donations are welcome at: AHzbs6oFvWmpbHCwRhEHK7WkrXBNt5wp2r "
	fi
done
